spring:
  application:
    name: lab_1_backend
  datasource:
      url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create-drop
    show-sql: true
server:
  port: 3228
